Rest api implementation
RisingStack/bootcamp-roland pull request #10
Opened 2020-10-09 12:15 UTC by rolandKoczan

Logger implementations

2020-10-09 12:26 UTC, simonzsolt requested changes

2020-10-09 12:26 UTC, simonzsolt commented on db/migrations/1-db-init.js
> +    logger.warn(error, 'Failed to migarte DB');
Shouldn't error messages have `error` as log level?

2020-10-09 12:26 UTC, simonzsolt commented on index.js
> +const httpLogger = require('express-pino-logger')({ logger: logger });
```suggestion
const httpLogger = require('express-pino-logger')({ logger });
```

2020-10-09 12:26 UTC, simonzsolt commented on index.js
> +    logger.warn(error.toString());
Also `error` log level.

2020-10-09 12:26 UTC, simonzsolt commented on index.js
> +app.listen(config.port, () => logger.info(`App is running on ${config.port}`));
```suggestion
app.listen(config.port, () => logger.info(`App is listening on port: ${config.port}`));
```

2020-10-12 12:19 UTC, kubischj approved these changes

2020-10-12 12:20 UTC, simonzsolt approved these changes

2020-10-12 12:21 UTC, merged