Implement helper functions for the database models
RisingStack/bootcamp-roland pull request #5
Opened 2020-09-23 12:47 UTC by rolandKoczan

2020-09-24 08:19 UTC, TamasHodi requested changes

2020-09-24 08:19 UTC, TamasHodi commented on index.js
> +const { request } = require('chai');
Chai should not be part of the application!

2020-09-24 08:19 UTC, TamasHodi commented on package.json
> +    "koa-bodyparser": "^4.3.0",
:tophat:

2020-09-24 08:19 UTC, TamasHodi commented on db/models/user.js
> +    type: Joi.string()
What kind of values can be inserted here? Could you please use an enum to restrict it?

2020-09-24 08:19 UTC, TamasHodi commented on db/models/user.js
> +    id: Joi.number().required(),
Please make it integer!

2020-09-24 08:19 UTC, TamasHodi commented on db/models/user.js
> +    avatar_url: Joi.string(),
You can validate these string and force to be `uri`s.

2020-09-24 08:19 UTC, TamasHodi commented on router.js
> +    ctx.body = await repositorySchema.insert({id, owner, full_name, html_url, description, language, stargazers_count});
Please return 40X in case the payload is malformed (with the proper error message in the response) and return 50X if something bad happened (without letting the stack trace leaking to the user)!

2020-09-24 08:19 UTC, TamasHodi commented on router.js
> +    ctx.body = await repositorySchema.insert({id, owner, full_name, html_url, description, language, stargazers_count});
Please apply the same error handling for all of our endpoints!

2020-09-24 08:19 UTC, TamasHodi commented on router.js
> +const { use } = require('chai');
Pls, remove this one as well!

2020-09-24 08:19 UTC, TamasHodi commented on router.js
> +router.get('/insertRepository', (ctx) => ctx.body = `
Pls, remove these endpoints and use `postman`, `curl` or any other tool which is capable to send HTTP requests!

2020-09-24 08:19 UTC, TamasHodi commented on router.js
> +router.get('/readRepository', async (ctx) => ctx.body = await repositorySchema.read({id: 1}));
Please use RESTful naming convention!

2020-09-24 08:19 UTC, TamasHodi commented on db/models/contribution.js
> +        VALUES (${user}, ${repository}, ${line_count})
Pls avoid using JS strings and templating, use knex against SQL injections!

2020-09-24 08:19 UTC, TamasHodi commented on db/models/contribution.js
> +        ON CONFLICT ("user", repository) DO UPDATE SET "user"=EXCLUDED."user", repository=EXCLUDED.repository, line_count=EXCLUDED.line_count
Pls remove `"user"=EXCLUDED."user", repository=EXCLUDED.repository` because we don't want to update these fields!

2020-09-24 08:19 UTC, TamasHodi commented on db/models/contribution.js
> +    const both = await db.raw(`
Please use knex as a query builder instead calling the raw method!

2020-09-24 19:20 UTC, rolandKoczan commented on db/models/user.js
> +    type: Joi.string()
I'm not sure what "type" represents. As I looked up on the github API page every entity has this property (repositories, users), as for users its value happens to be "User". I looked up the example project as well and in the seed file this column is set to "User". I don't understand why we need this column if all the records in this table are type of "User". I could set an enum to only accept "User", but that wouldn't make sense in my opinion.

2020-09-29 07:50 UTC, TamasHodi commented on db/models/user.js
> +    type: Joi.string()
In that case, I would just remove the field because it holds no extra information.

2020-09-29 07:51 UTC, closed without merging